"""
PPT 生成服务
根据论文结构和内容自动生成演示文稿
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import os
import tempfile
from typing import Dict, Optional
from app.core.logger import logger
from app.core.config import settings
from app.core.utils import generate_unique_id, ensure_directory_exists, get_timestamp

def generate_ppt(
    structure_data: Dict,
    include_images: bool = True,
    template: str = "default",
    options: Optional[Dict] = None,
    output_path: Optional[str] = None
) -> Dict:
    """
    根据论文结构生成 PPT
    
    参数:
    - structure_data: 论文结构分析数据
    - include_images: 是否包含图像
    - template: PPT 模板
    - options: 其他自定义选项
    - output_path: 输出路径（可选）
    
    返回:
    - 生成结果
    """
    logger.info(f"📊 开始生成 PPT，使用模板: {template}")
    
    try:
        # 创建演示文稿对象
        prs = Presentation()
        
        # 设置幻灯片尺寸（16:9）
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)
        
        # 添加标题页
        _add_title_slide(prs, structure_data, template)
        
        # 添加目录页
        _add_agenda_slide(prs, structure_data, template)
        
        # 为每个章节添加幻灯片
        sections = structure_data.get("sections_detected", [])
        for section in sections:
            _add_section_slide(prs, section, structure_data, template)
        
        # 添加结束页
        _add_closing_slide(prs, template)
        
        # 确定输出路径
        if not output_path:
            output_dir = os.path.join(settings.OUTPUT_DIR, "presentations")
            ensure_directory_exists(output_dir)
            filename = f"presentation_{get_timestamp()}_{generate_unique_id()[:8]}.pptx"
            output_path = os.path.join(output_dir, filename)
        
        # 保存 PPT
        prs.save(output_path)
        
        logger.info(f"✅ PPT 生成成功: {output_path}")
        
        return {
            "ppt_path": output_path,
            "slide_count": len(prs.slides),
            "template": template,
            "status": "success"
        }
    
    except Exception as e:
        logger.error(f"❌ PPT 生成失败: {str(e)}")
        raise

def _add_title_slide(prs: Presentation, structure_data: Dict, template: str):
    """
    添加标题页
    
    参数:
    - prs: Presentation 对象
    - structure_data: 结构数据
    - template: 模板名称
    """
    slide = prs.slides.add_slide(prs.slide_layouts[0])  # 使用标题布局
    
    # 设置标题
    title = slide.shapes.title
    title.text = structure_data.get("title", "Academic Paper Presentation")
    
    # 设置副标题
    if len(slide.placeholders) > 1:
        subtitle = slide.placeholders[1]
        subtitle.text = f"Based on Structure Analysis\nGenerated by AI Assistant"
    
    # 应用模板样式
    _apply_template_style(slide, template, "title")

def _add_agenda_slide(prs: Presentation, structure_data: Dict, template: str):
    """
    添加目录页
    
    参数:
    - prs: Presentation 对象
    - structure_data: 结构数据
    - template: 模板名称
    """
    slide = prs.slides.add_slide(prs.slide_layouts[1])  # 使用标题和内容布局
    
    title = slide.shapes.title
    title.text = "Agenda / 目录"
    
    # 添加章节列表
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.clear()
    
    sections = structure_data.get("sections_detected", [])
    for i, section in enumerate(sections, start=1):
        p = tf.add_paragraph()
        p.text = f"{i}. {section}"
        p.level = 0
        p.font.size = Pt(18)
    
    _apply_template_style(slide, template, "content")

def _add_section_slide(prs: Presentation, section: str, structure_data: Dict, template: str):
    """
    添加章节内容页
    
    参数:
    - prs: Presentation 对象
    - section: 章节名称
    - structure_data: 结构数据
    - template: 模板名称
    """
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    
    title = slide.shapes.title
    title.text = section
    
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.clear()
    
    # 获取章节详细信息
    section_details = structure_data.get("details", {}).get(section, {})
    
    # 添加内容要点
    bullet_points = [
        f"Key findings and contributions in {section}",
        f"Methodology and approach used",
        f"Results and analysis",
        f"Implications and future work"
    ]
    
    for point in bullet_points:
        p = tf.add_paragraph()
        p.text = point
        p.level = 0
        p.font.size = Pt(16)
    
    _apply_template_style(slide, template, "content")

def _add_closing_slide(prs: Presentation, template: str):
    """
    添加结束页
    
    参数:
    - prs: Presentation 对象
    - template: 模板名称
    """
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    
    title = slide.shapes.title
    title.text = "Thank You! / 谢谢!"
    
    if len(slide.placeholders) > 1:
        subtitle = slide.placeholders[1]
        subtitle.text = "Q&A / 问答环节"
    
    _apply_template_style(slide, template, "closing")

def _apply_template_style(slide, template: str, slide_type: str):
    """
    应用模板样式
    
    参数:
    - slide: 幻灯片对象
    - template: 模板名称
    - slide_type: 幻灯片类型
    """
    # 根据不同模板应用不同的样式
    if template == "academic":
        bg_color = RGBColor(245, 245, 245)  # 浅灰色背景
    elif template == "modern":
        bg_color = RGBColor(30, 30, 30)  # 深色背景
    else:  # default
        bg_color = RGBColor(255, 255, 255)  # 白色背景
    
    # 设置背景色
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = bg_color

def customize_ppt(ppt_path: str, customizations: Dict) -> Dict:
    """
    自定义 PPT 样式
    
    参数:
    - ppt_path: PPT 文件路径
    - customizations: 自定义配置
    
    返回:
    - 更新结果
    """
    logger.info(f"🎨 开始自定义 PPT: {ppt_path}")
    
    try:
        if not os.path.exists(ppt_path):
            raise FileNotFoundError(f"PPT 文件不存在: {ppt_path}")
        
        prs = Presentation(ppt_path)
        
        # 应用自定义设置
        theme = customizations.get("theme", {})
        font_settings = customizations.get("font", {})
        
        # 遍历所有幻灯片应用样式
        for slide in prs.slides:
            # 应用主题颜色
            if theme:
                background = slide.background
                fill = background.fill
                fill.solid()
                bg_color = theme.get("background_color", "ffffff")
                fill.fore_color.rgb = RGBColor(
                    int(bg_color[0:2], 16),
                    int(bg_color[2:4], 16),
                    int(bg_color[4:6], 16)
                )
            
            # 应用字体设置
            if font_settings:
                for shape in slide.shapes:
                    if hasattr(shape, "text_frame"):
                        for paragraph in shape.text_frame.paragraphs:
                            for run in paragraph.runs:
                                if "font_size" in font_settings:
                                    run.font.size = Pt(font_settings["font_size"])
                                if "font_name" in font_settings:
                                    run.font.name = font_settings["font_name"]
        
        # 保存修改
        prs.save(ppt_path)
        
        logger.info(f"✅ PPT 自定义完成: {ppt_path}")
        
        return {
            "ppt_path": ppt_path,
            "status": "success",
            "customizations_applied": list(customizations.keys())
        }
    
    except Exception as e:
        logger.error(f"❌ PPT 自定义失败: {str(e)}")
        raise

def add_image_to_slide(prs: Presentation, slide_index: int, image_path: str, position: tuple = None):
    """
    向指定幻灯片添加图像
    
    参数:
    - prs: Presentation 对象
    - slide_index: 幻灯片索引
    - image_path: 图像路径
    - position: 图像位置 (left, top, width, height)
    """
    try:
        slide = prs.slides[slide_index]
        
        if position:
            left, top, width, height = position
        else:
            left = Inches(1)
            top = Inches(2)
            width = Inches(4)
            height = Inches(3)
        
        slide.shapes.add_picture(image_path, left, top, width, height)
        
        logger.info(f"✅ 图像已添加到幻灯片 {slide_index + 1}")
    
    except Exception as e:
        logger.error(f"❌ 添加图像失败: {str(e)}")
